project:
  type: website
  output-dir: .

website:
  title: "Justin Andrew Johnson"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - href: about.ipynb
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



